#!/bin/sh
#
# Copyright 2013 Canonical Ltd.
#
# Author: Alberto Milone <alberto.milone@canonical.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
PRIME_LOG=/var/log/lightdm_prime_out.log
prime_settings=/etc/lightdm/hybrid_default
prime_power=/proc/acpi/bbswitch

if [ ! -e $prime_settings ]; then
    echo "No settings for prime can be found in $prime_settings" \
         > $PRIME_LOG 2>&1
    exit 0
fi

if [ ! -e $prime_power ]; then
    echo "No bbswitch can be found" \
         > $PRIME_LOG 2>&1
    exit 0
fi

nvidia_status="`cat $prime_power | cut -d " " -f2`"
action="`cat $prime_settings`"

# Do we need to change anything?
if [ "$action" = "$nvidia_status" ]; then
    echo "No action required to get PRIME to work" \
         > $PRIME_LOG 2>&1
    exit 0
fi

if [ "$action" = "ON" ]; then
    echo "Enabling the NVIDIA card" \
         > $PRIME_LOG 2>&1
    echo "ON" > /proc/acpi/bbswitch
    /sbin/modprobe nvidia || true
    exit 0
elif [ "$action" = "OFF" ]; then
    echo "Disabling the NVIDIA card" \
         > $PRIME_LOG 2>&1
    /sbin/rmmod nvidia || true
    echo "OFF" > /proc/acpi/bbswitch
    exit 0
else
    echo "\"$action\" is not a valid action for PRIME" \
         > $PRIME_LOG 2>&1
    exit 0
fi

